cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/services"

brew "ack"
brew "asdf"
brew "automake"
brew "awscli"
brew "bash"
brew "bat"
brew "cmake"
brew "coreutils"
brew "curl"
brew "direnv"
brew "dive"
brew "eza"
brew "fd"
brew "findutils"
brew "fzy"
brew "gcc"
brew "gh"
brew "gifski"
brew "git-delta"
brew "git"
brew "gnu-sed"
brew "gnupg"
brew "go"
brew "gpg"
brew "gzip"
brew "hopenpgp-tools"
brew "htop"
brew "icu4c"
brew "jemalloc"
brew "jq"
brew "mas"
brew "openssh"
brew "openssl"
brew "ossp-uuid"
brew "pinentry-mac" # yubikey
brew "pstree"
brew "readline"
brew "shellcheck"
brew "starship"
brew "swig" # yubikey
brew "terraform"
brew "unzip"
brew "vim"
brew "wget"
brew "xz"
brew "ykman" # yubikey
brew "yubico-piv-tool" # yubikey
brew "yubikey-personalization" # yubikey
brew "zig"
brew "zlib"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-fast-syntax-highlighting"
brew "zsh"

cask "1password-cli"
cask "1password"
cask "aldente"
cask "alt-tab"
cask "appcleaner"
cask "caption"
cask "dropshare"
cask "google-drive"
cask "iina"
cask "kap"
cask "little-snitch"
cask "modern-csv"
cask "muzzle"
cask "obsidian"
cask "orbstack" # docker
cask "oversight"
cask "postico"
cask "proxyman"
cask "raycast"
cask "shottr"
cask "spotify"
cask "temurin" # Java JDK
cask "transmission"
cask "ghostty"
cask "warp"
cask "zoom"
