#!/bin/bash
set -e

###############################################################################
# Mac
###############################################################################

./install/mac.sh

###############################################################################
# XCode Command Line Tools                                                    #
###############################################################################

./install/xcode.sh

###############################################################################
# Brew
###############################################################################

./install/brew.sh

# Install pre-requisites for setup
brew install stow
brew install zsh

# Make sure the folders aren't symlinked
mkdir ~/.aws ~/.bundle ~/.gnupg ~/.rbenv ~/.ssh ~/.secrets

# Symlink dotfiles
stow home -t ~/

###############################################################################
# zsh & iterm
###############################################################################

if [ $(echo $SHELL) != $(which zsh) ]; then
  sudo dscl . -create /Users/$USER UserShell $(which zsh)

  echo "Install the Solarized Dark theme for iTerm"
  echo "open \"${HOME}/dotfiles/iterm/Solarized Dark.itermcolors\""
fi

./setup
