#!/bin/bash
set -e

if ! [ -d ~/.gnupg ] || ! [ -d ~/.ssh ]
then
  echo "Run script/setup first!" >&2
  exit 1
fi

onepassword_login() {
  if ! command -v op >/dev/null
  then
    echo "Install op first!" >&2
    exit 1
  fi

  # shellcheck disable=SC2154
  if [ -z "$OP_SESSION_feelepxyz" ]
  then
    echo "Logging into 1Password..."
    eval "$(op signin my.1password.com philip@mailharrison.com)"
  fi
}

onepassword_get() {
  if [ -f "$HOME/$2" ]
  then
    echo "$HOME/$2 already exists."
    return
  fi
  echo "Extracting $2..."
  onepassword_login
  op get document "$1" --vault="j2kzzjxmhp5hexbvbzab66g3vy" > "$HOME/$2"
  chmod 600 "$HOME/$2"
}

onepassword_get eqcnnr7wsljydy3wijkp3656yi .secrets/credentials
onepassword_get lwwa3g5rrpfl5yncdgm4zffy5q .secrets/scripts

echo "Setting up GPG..."
if ! command -v gpg >/dev/null
then
    echo "Install GPG first!" >&2
    exit 1
fi

chmod 700 ~/.gnupg
gpg --import ~/.gnupg/philip@mailharrison.com.public.gpg-key
