#!/bin/bash
set -e

onepassword_login() {
  if ! command -v op >/dev/null
  then
    echo "Install op first!" >&2
    exit 1
  fi

  # shellcheck disable=SC2154
  if [ -z "$OP_SESSION_my" ]
  then
    echo "Logging into 1Password..."
    eval "$(op signin my.1password.com philip@mailharrison.com)"
  fi
}

onepassword_get() {
  if [ -f "$2" ]
  then
    echo "$2 already exists."
    return
  fi
  echo "Extracting $2..."
  onepassword_login
  op get document "$1" --vault="j2kzzjxmhp5hexbvbzab66g3vy" > "$2"
  chmod 600 "$2"
}

mkdir -p $HOME/.secrets/
onepassword_get cchchkfrsrbm3ltg4rd3zhpooi $HOME/.secrets/connect-github.applescript
onepassword_get plgass3uwbcjvckes677lyttua $HOME/.secrets/scripts
