#!/usr/bin/env bash
# Add logging
exec > >(tee -i $HOME/dotfiles_install.log)
exec 2>&1
set -x

# Install all dotfiles into the home directory
if [ -L "$0" ]
then
  SCRIPTSETUP="$(readlink "$0")"
else
  SCRIPTSETUP="$0"
fi

DOTFILESDIRREL=$(dirname $SCRIPTSETUP)
cd $DOTFILESDIRREL/../home/
DOTFILESDIR=$(pwd -P)

UNAME_S="$(uname -s)"
[[ "${UNAME_S}" = "Darwin" ]] && export MACOS=1
[[ "${UNAME_S}" = "Linux" ]] && export LINUX=1
[[ "${UNAME_S}" == *_NT-* ]] && export WINDOWS=1
[[ -n "${LINUX}" ]] && grep -qEi "(Microsoft|WSL)" /proc/version && export WSL=1

if [ $MACOS ]
then
  echo "Installing from user Brewfile"
  brew bundle check --file .Brewfile || brew bundle --file .Brewfile 2> /dev/null
fi

for DOTFILE in *; do
  HOMEFILE="${HOME}/.${DOTFILE}"
  if [[ -d "${DOTFILE}" ]]; then
    DOTFILE="${DOTFILE}/"
    IS_DIR=1
  else
    IS_DIR=
  fi
  DIRFILE="${DOTFILESDIR}/${DOTFILE}"

  # Don't mess with Codespaces' default SSH setup.
  if [[ -n "${CODESPACES}" && "${DOTFILE}" = "ssh/" ]]; then
    continue
  fi

  if [[ -z "${IS_DIR}" ]]; then
    [[ "${HOMEFILE}" -ef "${DIRFILE}" ]] && continue
    if [[ -L "${HOMEFILE}" ]]; then
      ln -sf "${DIRFILE}" "${HOMEFILE}"
    else
      ln -svf "${DIRFILE}" "${HOMEFILE}"
    fi
  elif [[ "${HOMEFILE}" -ef "${DIRFILE}" ]]; then
    continue
  elif [[ -L "${HOMEFILE}" ]]; then
    rm -r "${HOMEFILE}" 2>/dev/null
    ln -s "${DIRFILE}" "${HOMEFILE}"
  else
    rm -rfv "${HOMEFILE}" 2>/dev/null
    ln -sv "${DIRFILE}" "${HOMEFILE}"
  fi
done
