#!/bin/sh
set -e

# Install all dotfiles into the home directory
if [ -L "$0" ]
then
  SCRIPTSETUP="$(readlink "$0")"
else
  SCRIPTSETUP="$0"
fi

DOTFILESDIRREL=$(dirname $SCRIPTSETUP)
cd $DOTFILESDIRREL/../home/
DOTFILESDIR=$(pwd -P)

[ $(uname -s) = "Darwin" ] && export MACOS=1 && export UNIX=1
[ $(uname -s) = "Linux" ] && export LINUX=1 && export UNIX=1
uname -s | grep -q "_NT-" && export WINDOWS=1

if [ $MACOS ]
then
  VSCODE="$HOME/Library/Application Support/Code/User"
elif [ $LINUX ]
then
  VSCODE="$HOME/.config/Code/User"
elif [ $WINDOWS ]
then
  VSCODE="$APPDATA/Code/User"
fi

if [ $MACOS ]
then
  echo "Installing from user Brewfile"
  brew bundle check --file .Brewfile || brew bundle --file .Brewfile
fi

for DOTFILE in .[^.]* .[^.]*/* .[^.]*/.[^.]*; do
  HOMEFILE="$HOME/$DOTFILE"
  [ -d $DOTFILE ] && DOTFILE="$DOTFILE/"
  DIRFILE="$DOTFILESDIR/$DOTFILE"
  # Skip glob paths
  [ ! -d $DIRFILE ] && [ ! -f $DIRFILE ] && continue

  # Don't mess with Codespaces' default GPG/SSH setup.
  if [ -n "$CODESPACES" ]
  then
    echo $DOTFILE | egrep -q '^(gnupg|ssh)/' && continue
  fi

  if [ $UNIX ]
  then
    if [ -L "$HOMEFILE" ] && ! [ -d $DOTFILE ]
    then
      ln -sfv "$DIRFILE" "$HOMEFILE"
    else
      if [ -d $DOTFILE ]
      then
        mkdir -p "$HOMEFILE"
      else
        ln -sv "$DIRFILE" "$HOMEFILE"
      fi
    fi
  else
    cp -rv "$DIRFILE" "$HOMEFILE"
  fi
done

if [ -n "$CODESPACES" ]
then
  # Fix up Codespaces permissions
  chmod 700 /workspaces

  # Send notification that dotfiles setup has completed
  curl --silent \
    --form-string "token=$PUSHOVER_API_TOKEN" \
    --form-string "user=$PUSHOVER_USER_KEY" \
    --form-string "message=dotfiles script/setup complete for $CODESPACE_NAME!" \
    https://api.pushover.net/1/messages.json
fi

# Fix permissions
chmod 700 ~/.gnupg

if [ ! -n "$CODESPACES" ]
then
  chmod 400 ~/.ssh/id_rsa_yubikey
fi
