#!/bin/bash
set -e

[ $(uname -s) = "Darwin" ] && export MACOS=1

if [ $MACOS ]
then
  ../install/mac.sh
fi

# Set zsh as the default shell
if [ "$SHELL" != "/bin/zsh" ]
then
  chsh -s /bin/zsh $USER
fi

echo "Install the Solarized Dark theme for iTerm"
echo "open \"${HOME}/.dotfiles/iterm/Solarized Dark.itermcolors\""

# Import key used for signing
gpg --import ~/.gnupg/philip@mailharrison.com.public.gpg-key

echo "Update gpg key trust"
echo "$ gpg --edit-key $KEYID"

./extract-onepassword-secrets
