#!/bin/bash
set -e

SCRIPTSREL=$(dirname $0)

[ $(uname -s) = "Darwin" ] && export MACOS=1

# Set zsh as the default shell
if [ "$SHELL" != "/bin/zsh" ]
then
  chsh -s /bin/zsh $USER
fi

# Import key used for signing
gpg --import ~/.gnupg/philip@mailharrison.com.public.gpg-key

if [ $MACOS ]
then
  $SCRIPTSREL/../install/mac.sh
fi
