#!/bin/bash
set -euo pipefail

SCRIPTSREL="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

[[ "$(uname -s)" == Darwin ]] || exit 0

# Enable Touch ID for sudo
"$SCRIPTSREL/touchid-enable-pam-sudo" --quiet || true

# Set zsh as the default shell
if [ "${SHELL:-}" != "/bin/zsh" ]
then
  chsh -s /bin/zsh "$USER"
fi

"$SCRIPTSREL/../install/mac.sh"
